# Generated by Django 5.1 on 2024-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz_cyr',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz_cyr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz_cyr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
