# Generated by Django 5.1 on 2024-08-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_categories_slug_categories_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name_uz_cyr',
            new_name='name_eng',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_uz_cyr',
            new_name='content_eng',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_uz_cyr',
            new_name='title_eng',
        ),
    ]
