# Generated by Django 5.1 on 2024-08-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_name_uz_cyr_categories_name_eng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name_eng',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_eng',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_eng',
            new_name='title_en',
        ),
    ]
