# Generated by Django 4.2 on 2024-08-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_rename_name_eng_categories_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user', models.ForeignKey(default=None, help_text='User that created last translation version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_translation', to=settings.AUTH_USER_MODEL, verbose_name='User translator')),
            ],
        ),
    ]
